sonar.projectKey=devsecops-ci-cd_secure-ci-cd
sonar.organization=devsecops-ci-cd
sonar.sources=.
sonar.exclusions=**/seed.sql,**/*.md,**/static/**,**/__pycache__/**

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.branch.name=main
sonar.defaultBranch=main

